### ISSUE TITLE
Doc: Transfer embedded linux intro doc into markdown and add to documentation repo.

### ISSUE THREAD

**Issue by btam8703** [AlbertaSat/ex3_documentation#3]
Convert the following doc into markdown format, and add it to the documentation repo. This is so our team can slowly move away from google docs for documentation and instead use markdown files in github repos. 

https://docs.google.com/document/d/1hTB31M3i9ML0qjcBVeHZdQ-cc0JnZzqu339hxukDt80/edit?usp=sharing  

Acceptance criteria: 
- Document is transferred with all current info into a replica with markdown file format.

**Comment by btam8703** [comment]
There are several parts of the original doc that are unfinished - see the following:

![Image](https://github.com/AlbertaSat/ex3_documentation/assets/61596434/f0e29189-2cd8-4c34-a1dd-78be5e8b09af)

![Image](https://github.com/AlbertaSat/ex3_documentation/assets/61596434/6f331801-064c-4bec-b943-831c9e2b451c)

What should I do with these parts? Currently I am copying them word for word but is there something else I should do?
Also I think I accidentally put myself as the author of this Todo item and removed Devin's name - not sure how to reverse this but sorry about that.

**Comment by dheadrick1618** [comment]
Apologies I just saw this now. Feel free to ' @ ' myself or any team members for questions or concerns. Leave yourself as the assignee to this item that is fine. The goal was to transfer what has been done in the google doc here, so we may continue adding to it as a markdown file rather than something in the drive.  Great work! I suggest making a pull request now to merge this with main. Be sure to move the issue to the 'requires review' column in our project kanban.

**Comment by btam8703** [comment]
Thank you! Merge request is created and issue has been moved to 'requires review'.

**Comment by btam8703** [comment]
#
